### ISSUE TITLE
Wordfence reports IG Syntax Highlighter as abandoned

### ISSUE THREAD

**Issue by justdave** [coolamit/ig-syntax-hiliter#5]
WordFence security scan currently reports IG Syntax Highlighter as abandoned and encourages users to uninstall it, presumably because it hasn't been updated in 3 years.  I suspect bumping the compatibility indicators to the current version and pushing a new release with that will probably be plenty to make it happy even if there's nothing else new in it.

**Comment by justdave** [comment]
**Plugin Name:** iG:Syntax Hiliter
**Current Plugin Version:** 5.1
**Last Updated:** May 6, 2022

**Details:** It was last updated 2 years 11 months ago and tested up to WordPress 5.9.10. It may have compatibility problems with the current version of WordPress or unknown security issues. [Get more information.](https://www.wordfence.com/help/?query=scan-result-plugin-abandoned)

**Comment by coolamit** [comment]
@justdave Thanks for reporting. I'll roll out a version bump for this shortly.

**Comment by ozh** [comment]
Just reporting in, that I'm still using this plugin (since probably it first came out 😄 )

A dark mode would be killer if you ever feel like adding one ! Thanks for the plugin

**Comment by ozh** [comment]
For the record, simple solving of the dark/light compat with this snippet in my theme css : 

```css
/* igsyntax-hiliter plugin - dark mode adaptation
   invert(1) hue-rotate(180deg) : turns white bg to dark and keeps syntax colors coherent */
[data-theme="dark"] .entry-content div.syntax_hilite {
  filter: invert(1) hue-rotate(180deg);
  border-radius: var(--r-md);
  overflow: hidden;
}
```

Credits to Claude, I suck way too much at CSS.
